import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {AiFillTwitterCircle, AiFillLinkedin,AiFillGithub} from 'react-icons/ai'
import Image from "next/legacy/image"
const inter = Inter({ subsets: ["latin"] });
import fe from '../public/dev-fe-wave.png';
export default function Home() {
  return (
    <>
      <Head>
        <title>Fulya Ertay Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">developedbyfe</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl"></BsFillMoonStarsFill>
              </li>
              <li>
                <a  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 roundedn-md ml-8"href="#">Resume</a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">Fulya Ertay</h2>
            <h3 className="text-2xl py-2">Junior Software Developer</h3>
            <p className="text-md py-5 leading-8 text-gray-800">Providing services for user-friendly web applications. Join me down below and collaborate on awesome projects! </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3">
            <a href="https://twitter.com/Fulinin_"><AiFillTwitterCircle></AiFillTwitterCircle></a>
            <a href="https://www.linkedin.com/in/fulya-ertay-40a593156/"><AiFillLinkedin></AiFillLinkedin></a>
            <a href="https://github.com/fulyaertay"><AiFillGithub></AiFillGithub></a>
          
          
          </div>
          <div className="relative rounded-full w-80 h-80 mt-20 mx-auto" >
            <Image src={fe}></Image>
          </div>
        </section>
      </main>
    </>
  );
}
